# Generated by Django 4.1.7 on 2023-05-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPRLP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('action_time', models.DateTimeField()),
                ('applier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_applier', to=settings.AUTH_USER_MODEL)),
                ('assigment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SPRLP.assignment')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
