# Generated by Django 4.1.7 on 2023-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPRLP', '0002_actionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1500)),
            ],
        ),
    ]
