# Generated by Django 4.1.7 on 2023-05-31 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPRLP', '0004_responsemessage_delete_responsemessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseMessage',
        ),
    ]
